name = "bfeederdcm"
chain = "base"
address = "0x91582e8f7684cB41261BB136C691D82b4EcEDe8A"

[calibers.base]
address = "0xbfdc3cc9C8916300f546D7b31667731F5f6536e0"
swapper = "0xe87596d490f1118dfe64a75498c82b997e539d4b"
rootfiles = "github:MakinaHQ/makina-integrations/machines/bfeederdcm/base/rootfiles"

[calibers.base.accounting_token]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.mainnet]
address = "0xbfdc3cc9c8916300f546d7b31667731f5f6536e0"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-integrations/machines/bfeederdcm/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
name = "USD Coin"
symbol = "USDC"
